services:  
  flink-jobmanager:
    image: flink:1.19
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - 'FLINK_PROPERTIES=jobmanager.rpc.address: flink-jobmanager'
    restart: always
    networks:
      - pipeline-net

  flink-taskmanager:
    image: flink:1.19
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - 'FLINK_PROPERTIES=jobmanager.rpc.address: flink-jobmanager'
    restart: always
    networks:
      - pipeline-net

  pyflink-job:
    build:
      context: ./pyflink-job
    command: >
      bash -c "sleep 15 && /opt/flink/bin/flink run -t remote -m flink-jobmanager:8081 -py /opt/pyflink/pyflink_job.py"
    depends_on:
      - kafka
      - flink-jobmanager
      - flink-taskmanager
    networks:
      - pipeline-net

networks:
  pipeline-net:
    external: true